### ISSUE TITLE
[Plus] AIZRockPile cannot be broken when both smashSides and smashTop are disabled.

### ISSUE THREAD

**Issue by LittlePlanetCD** [RSDKModding/Sonic-Mania-Decompilation#276]
In the steam version, if both smashSides and smashTop are disabled, AIZRockPile will be able to be broken by either by the sides or top.

in the decomp, when both smashSides and smashTop are disabled, AIZRockPile becomes indestructible. This is technically incorrect behavior.

**Comment by Mefiresu** [comment]
This issue is actually invalid, as these booleans aren't even unused in the original.
[f18ca79](https://github.com/RSDKModding/Sonic-Mania-Decompilation/commit/f18ca797b5847d181e2f640e3283c89feab30628) is somewhat related and fixed some inaccuracies.
