### ISSUE TITLE
Camera switches to capsule before defeating boss on Press Garden act 2

### ISSUE THREAD

**Issue by Wolfydev** [RSDKModding/Sonic-Mania-Decompilation#288]
This basically. 
https://github.com/user-attachments/assets/242d2f7a-a60e-46da-94f8-97e47d7b01b0

**Comment by MegAmi24** [comment]
This happens because you're playing with a higher screen width than the game is designed for. You can use the [UltrawideMania](https://github.com/RSDKModding/RSDKv5-Example-Mods/tree/master/UltrawideMania) mod to fix this issue, but there's nothing we can do here.

**Comment by Wolfydev** [comment]
This sounds stupid from me to ask, but how do I download it?

**Comment by Wolfydev** [comment]
Thank you so much, btw I have 2 other problems..

1. In after act 1 of flying battery zone, cutscene plays and doesn't let me in act 2 (Unless I press 'restart' in dev menu)
2. Game sometimes slowns down/speeds up for few seconds, and then it normalizes.


Is it possible to fix those?

**Comment by Wolfydev** [comment]
Update: UltrawideMania only makes buttons smaller, nothing else...
