### ISSUE TITLE
Built, but there are no executables anywhere (Arch Linux)

### ISSUE THREAD

**Issue by Melechtna** [RSDKModding/Sonic-Mania-Decompilation#291]
Title says it all, there is a .so file in the build folder, but this isn't an executable, and I have no idea where the actual executable is, and this isn't explained anywhere. Given the hundreds of programs I've built and developed, this really shouldn't even come close to confusing.

**Comment by MegAmi24** [comment]
Building Sonic Mania only builds the game itself, i.e. the .so file you mentioned. The executable you're expecting is RSDKv5, which is only built by either adding `-DWITH_RSDK=on` to the first cmake build command or by building [this repository](https://github.com/RSDKModding/RSDKv5-Decompilation).

**Comment by Mefiresu** [comment]
> Building Sonic Mania only builds the game itself, i.e. the .so file you mentioned. The executable you're expecting is RSDKv5, which is only built by either adding `-DWITH_RSDK=on` to the first cmake build command or by building [this repository](https://github.com/RSDKModding/RSDKv5-Decompilation).

Not quite correct actually, `WITH_RSDK` is enabled by default and will build RSDKv5 at the same time as Mania (on Linux at least, provided you built using cmake).
The executable file will be in `build/dependencies/RSDKv5` (`RSDKv5U` or `RSDKv5` depending on the game revision).
