### ISSUE TITLE
Very specific collision inaccuracy 

### ISSUE THREAD

**Issue by Jdaslepre** [RSDKModding/Sonic-Mania-Decompilation#293]
Unsure if this is a bug with knuckles' glide ability, an engine collision bug, or a bug with mania's PimPom object. (also sorry for the undescriptive title, couldn't think of anything better)

As knuckles, gliding into (for example, this PimPom object in Studiopolis Act 2, at `x: 4816, y: 1776`) will cause the player to clip into the roof, instead of continuing as normal

- Decomp: https://drive.google.com/file/d/1Xa8MFt2XBxpfuYHesPA28WW3uOOC5LVi/view?usp=sharing
- Steam: https://drive.google.com/file/d/1OtJP_Z8H21JyPVCd7S2fTQimDSRygLKG/view?usp=sharing
- Netflix: https://drive.google.com/file/d/1vV1PPB-9ZOChlYjKEHTCmEUCx6Q174zR/view?usp=sharing

Base RSDKv5, Windows - MSVC x64
Also tested with RSDKv5U, which has the same behavior

**Comment by Mefiresu** [comment]
Fixed by https://github.com/RSDKModding/RSDKv5-Decompilation/commit/df6e1690e14a6520ce651483f8bfc29cec308166
