### ISSUE TITLE
the discord server link isn't working/down

### ISSUE THREAD

**Issue by DaRandomCube** [RSDKModding/Sonic-Mania-Decompilation#296]
### Before opening this issue, I ensure that...

- [X] I have read the [FAQ](https://github.com/RSDKModding/Sonic-Mania-Decompilation?tab=readme-ov-file#faq) and confirmed my issue is not mentioned in it.
- [X] I have checked **both open and closed** issues and confirmed this bug has not already been reported.
- [X] I am not asking for tech support (e.g. game closing on startup, error when trying to build, etc).
- [X] I am not asking for modding support or reporting a bug in a specific mod; this bug either occurs without mods enabled or is directly related to the mod loader.
- [X] This bug is not related to any unofficial fork/port of the decompilation, and any issues with those should be kept in the appropriate repository.

### Expected Behavior

being able to join the server

### Actual Behavior

the link isn't working

### Steps to Reproduce

1. you have a question
2. try to see if it's answered in discord
3. the link is down and you can't join

### Decompilation Version

1.1.0

### Game Version

1.00 - 1.02 (Initial console release)

### Engine Revision

REV0U (RSDKv5U)

### Platform

fedora 41

### Additional Comments

i know it's not a bug report, but what should i do as the whole link is down...

**Comment by MegAmi24** [comment]
Just tested it and it worked fine for me. It's likely an issue on your end. Closing as it's not related to the decomp.
