### ISSUE TITLE
RNG functions broken: modulo by zero when `min` and `max` arguments are the same value

### ISSUE THREAD

**Issue by Sonic-The-Hedgehog-LNK1123** [RSDKModding/Sonic-Mania-Decompilation#302]
### Before opening this issue, I ensure that...

- [X] I have read the [FAQ](https://github.com/RSDKModding/RSDKv5-Decompilation/blob/main/FAQ.md) and confirmed my issue is not mentioned in it.
- [X] I have checked **both open and closed** issues and confirmed this bug has not already been reported.
- [X] I am not asking for tech support (e.g. game closing on startup, error when trying to build, etc).
- [X] I am not asking for modding support or reporting a bug in a specific mod; this bug either occurs without mods enabled or is directly related to the mod loader.
- [X] This bug is not related to any unofficial fork/port of the decompilation, and any issues with those should be kept in the appropriate repository.

### Expected Behavior

Game should never crash in the RNG function

### Actual Behavior

Game does sometimes crash in the RNG function

### Steps to Reproduce

1. Start Sonic Mania (Blue Spheres in Extras menu must be unlocked)
2. Start a Blue Spheres game, Mania version
3. Repeat step 2 until there's only **one pink sphere** in the **entire** level
4. Touch the pink sphere

### Decompilation Version

RSDKv5 + U 1.1.0: The SHC2024 Update (1220d91)

### Engine Revision

REV0U (RSDKv5U)

### Backend

DirectX 9

### Platform

Windows 10

### Additional Comments

The RNG functions changed in commit 32b1ca3 will cause a modulo by 0 error when it's `min` and `max` arguments are the same value.
The **Steam** version of Sonic Mania does not crash when the steps in the `Reproduce` section are performed (Neither does the **Nintendo Switch** version).
**Decomp** builds prior this change also don't crash.
I don't have the **EGS** version, but since the commit message says: `Rand now matches the EGS assembly` it might crash in that case? (can someone with the EGS version please verify this?)

The RNG functions prior this change were properly guarded from division by 0.

**Comment by Sonic-The-Hedgehog-LNK1123** [comment]
@LittlePlanetCD If your claim is correct, then this is one of the worst RNG functions I've ever seen, having to be very certain your inputs for the `min` and `max` arguments aren't the same value is really strange, instead of just returning the input value, it actually invokes **undefined behavior**. Also this causes you having to insert such checks at every place you call the RNG, unless the values just can't be the same due to the surrounding code that computed them.

> This doesn't seem to be a Engine-sided issue. It's actually an error in the Sonic Mania decompilation.
> I can confirm, as i loaded the original steam code within the engine decompilation binaries and it did not crash.

Interesting, you can inject the original steam code into the decompilation?

**Comment by LittlePlanetCD** [comment]
> Interesting, you can inject the original steam code into the decompilation?
>

Correct, I can do so. I made a loader on my end that allows me to link into manias code from the steam binary to test any possible errors that could be game or engine sided.

An inverse was created my SuperSonic16, allowing users to load the Mania decomp DLL in place of the original steam logic.
